apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: welcome-java
  template:
    metadata:
      labels:
        app: welcome-java
    spec:
      containers:
      - name: welcome-java-app
        image: prasad315/java-welcome-app:v9
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: welcome-java-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: welcome-java
